<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\AccountController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.mqe7m41']) ? $this->services['service_locator.mqe7m41'] : $this->load(__DIR__.'/getServiceLocator_Mqe7m41Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Admin\\RestaurantController:formAction' => function () {
    return ${($_ = isset($this->services['service_locator.feydlg.']) ? $this->services['service_locator.feydlg.'] : $this->load(__DIR__.'/getServiceLocator_Feydlg_Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Admin\\RestaurantController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.kefgcpw']) ? $this->services['service_locator.kefgcpw'] : $this->load(__DIR__.'/getServiceLocator_KefgcpwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AjaxController:datalistAction' => function () {
    return ${($_ = isset($this->services['service_locator.altxhbj']) ? $this->services['service_locator.altxhbj'] : $this->load(__DIR__.'/getServiceLocator_AltxhbjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Profile\\AddCommentController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.o3xqk9g']) ? $this->services['service_locator.o3xqk9g'] : $this->load(__DIR__.'/getServiceLocator_O3xqk9gService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SearchByFilterController:indexFilterAction' => function () {
    return ${($_ = isset($this->services['service_locator.512xkaz']) ? $this->services['service_locator.512xkaz'] : $this->load(__DIR__.'/getServiceLocator_512xkazService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SearchByRegionController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.2vqrzq1']) ? $this->services['service_locator.2vqrzq1'] : $this->load(__DIR__.'/getServiceLocator_2vqrzq1Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SearchController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.157n_s4']) ? $this->services['service_locator.157n_s4'] : $this->load(__DIR__.'/getServiceLocator_157nS4Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController:login' => function () {
    return ${($_ = isset($this->services['service_locator.ax3ajkk']) ? $this->services['service_locator.ax3ajkk'] : $this->load(__DIR__.'/getServiceLocator_Ax3ajkkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.mqe7m41']) ? $this->services['service_locator.mqe7m41'] : $this->load(__DIR__.'/getServiceLocator_Mqe7m41Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Admin\\RestaurantController::formAction' => function () {
    return ${($_ = isset($this->services['service_locator.feydlg.']) ? $this->services['service_locator.feydlg.'] : $this->load(__DIR__.'/getServiceLocator_Feydlg_Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Admin\\RestaurantController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.kefgcpw']) ? $this->services['service_locator.kefgcpw'] : $this->load(__DIR__.'/getServiceLocator_KefgcpwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AjaxController::datalistAction' => function () {
    return ${($_ = isset($this->services['service_locator.altxhbj']) ? $this->services['service_locator.altxhbj'] : $this->load(__DIR__.'/getServiceLocator_AltxhbjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Profile\\AddCommentController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.o3xqk9g']) ? $this->services['service_locator.o3xqk9g'] : $this->load(__DIR__.'/getServiceLocator_O3xqk9gService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SearchByFilterController::indexFilterAction' => function () {
    return ${($_ = isset($this->services['service_locator.512xkaz']) ? $this->services['service_locator.512xkaz'] : $this->load(__DIR__.'/getServiceLocator_512xkazService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SearchByRegionController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.2vqrzq1']) ? $this->services['service_locator.2vqrzq1'] : $this->load(__DIR__.'/getServiceLocator_2vqrzq1Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SearchController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.157n_s4']) ? $this->services['service_locator.157n_s4'] : $this->load(__DIR__.'/getServiceLocator_157nS4Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SecurityController::login' => function () {
    return ${($_ = isset($this->services['service_locator.ax3ajkk']) ? $this->services['service_locator.ax3ajkk'] : $this->load(__DIR__.'/getServiceLocator_Ax3ajkkService.php')) && false ?: '_'};
})));
