<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.in_memory' shared service.

return $this->services['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(array('admin' => array('password' => '$2y$13$VKlsW467M.rK4z0boaRJteAXmMG7Y5a04EbhHq/1UD8kgCeM4SpZ6', 'roles' => array(0 => 'ROLE_ADMIN'))));
