# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$VKlsW467M.rK4z0boaRJteAXmMG7Y5a04EbhHq/1UD8kgCeM4SpZ6
                        roles: 'ROLE_ADMIN'


        our_db_provider:
            entity:
                class: AppBundle\Entity\user
                property: username

    # créer un provider regroupant les autres providers
        all_providers:
            chain:
                providers: [ in_memory, our_db_provider ]


    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

        AppBundle\Entity\user: plaintext


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                login_path: security.login
                check_path: security.login
                default_target_path: security.redirect.by.role

            logout:
                 path: security.logout
                 target: homepage.index

             #utiliser le regroupement de providers
            provider: all_providers