<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTnfowjw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTnfowjw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTnfowjw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTnfowjw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTnfowjw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tnfowjw',
    'container.build_id' => '40713848',
    'container.build_time' => 1519411955,
));
